### ISSUE TITLE
Alternate question mark replacement in #mock

### ISSUE THREAD

**Issue by tyler569** [davidgarland/digirc#5]
Currently, `#mock` replaces `?` characters with `¿` inverted question marks unconditionally. I think it would better match the style of the command if they alternated to match the caps/non caps behavior of the rest of `#mock`.

Example:
`#mock hello????????`
desired output:
`hElLo?¿?¿?¿?¿?¿`

**Comment by davidgarland** [comment]
Fixed as of https://github.com/davidgarland/digirc/commit/dca6ae8bfcb769a35a40eec86d37f5b26862d423.
